config/routes.rb
MyGists::Application.routes.draw do
  resources :gists
  root to: 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base


self.per_page = 6

def self.search(search)
	if search
		find(:all, :conditions => ['description LIKE ?',"%#{search}%"])
	else
		find(:all)
	end
end	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
       @gists = Gist.paginate(:page => params[:page]).search(params[:search])
			respond_to do |format|
			format.html
			format.js
		end
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
<% lex = Pygments::Lexer.all.select{|y| !(y.filenames.empty?)}.map{|x|[x.name, x.filenames.first.gsub('*','')]}.sort %>
<%
  all_lexers = Pygments.lexers.flatten.select.with_index(offset = 0) { |x,i| i % 2 == 0 }.sort
  all_lexers = all_lexers.delete_if { |x| x =~ /.\s./ }
  all_lexers = all_lexers.map { |x| x.downcase }
%>

  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet, :size => "80x20" %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.select :lang, all_lexers %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gists/_gist.html.erb
<div style="width:100%; margin-bottom: 65px;"> 

      <div> 
		Language: <%= gist.lang %>
      </div>

      <div>
		Description: <%= gist.description[0,20] %>
      </div>

      <div class="snippet ">
		<%= raw Pygments.highlight(gist.snippet.length > 20 ? gist.snippet[0,20] + "..." : gist.snippet, lexer: gist.lang) %>
      </div>

      <div class=>
              <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger",style:"float: right" %>
              <%= link_to 'Edit', edit_gist_path(gist), class: "btn btn-warning",style:" float: right; margin-right: 15px" %>
	      <%= link_to 'Show', gist, class: "btn btn-primary",style:"float : right; margin-right: 15px" %>
      </div>

</div>

app/views/gists/_index.html.erb
<div class="header bg-primary" style="z-index:10;">
<a href="gists" class="btn btn-primary btn-lg active" role="button"> Main Page</a>
<a href="https://github.com/KLamkiewicz/RubyGist" class="btn btn-primary btn-lg active" role="button"> Github</a>

<form class="navbar-form navbar-right" role="form">
Description
                <%= form_tag gists_path, :method => 'get' do %>
                 <%= (text_field_tag :search, params[:search], class:'form-control') %>
                <%= submit_tag "Search", class:'btn btn-warning' , :name => nil, :onclick => "$( document ).ready;"%>
               
               
                <% end %>
                
</form>

</div>

app/views/gists/edit.html.erb
<div class="header bg-primary">
	<a href="/gists" class="btn btn-primary btn-lg active" role="button"> Main Page</a>
	<a href="https://github.com/KLamkiewicz/RubyGist" class="btn btn-primary btn-lg active" role="button"> Github</a>
</div>

<div class="main">
<h1>Editing gist</h1>


<%= render 'form' %>

<%= link_to 'Show', @gist %> |

<%= link_to 'Back', gists_path %>

</div>

app/views/gists/index.html.erb
<%= render 'index' %>

<div style="padding-top:200px; text-align: center; font-size: 60px;"> My gists</div>


<div style="padding-top:40px; float: right"> <%= link_to 'New Gist', new_gist_path, class:'btn btn-success btn-lg' %> </div>


<div class="main center-block" >

<table id="gists" style="width:100%;" > 
  <%= render @gists %>
</table>

<div id="infinite-scrolling">
  <%= will_paginate %>
</div>

</div>

app/views/gists/index.js.erb
$('#gists').append('<%= j render @gists %>');
<% if @gists.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @gists %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/gists/new.html.erb
<div class="header bg-primary">
	<a href="/gists" class="btn btn-primary btn-lg active" role="button"> Main Page</a>
	<a href="https://github.com/KLamkiewicz/RubyGist" class="btn btn-primary btn-lg active" role="button"> Github</a>
</div>

<div class="main">

<h1>New gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path %>

</div>

app/views/gists/show.html.erb
<div class="header bg-primary">
	<a href="/gists" class="btn btn-primary btn-lg active" role="button"> Main Page</a>
	<a href="https://github.com/KLamkiewicz/RubyGist" class="btn btn-primary btn-lg active" role="button"> Github</a>
</div>

<div class="main">

<p id="notice"><%= notice %></p>

<p>
  <strong>Snippet:</strong>
  <%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @gist.lang %>
</p>



<p>
  <strong>Description:</strong>
  <%= @gist.description %>
</p>

<%= link_to 'Edit', edit_gist_path(@gist) %> |
<%= link_to 'Back', gists_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>